# Generated by Django 3.2.15 on 2022-10-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=255, verbose_name='Doctors Availble')),
                ('time_slot', models.CharField(max_length=255, verbose_name='Timing')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='myapp.doctor', verbose_name='Doctor')),
            ],
        ),
    ]
